Add VARIABLE_DEFINITION directive location
graphql-rust/graphql-parser pull request #66
Opened 2022-06-27 13:49 UTC by vmagro

I have some schemas that have this directive location, and this crate
currently crashes while trying to parse it.

2022-07-03 07:40 UTC, dotansimha approved these changes

2022-08-04 15:03 UTC, LegNeato requested changes
Thank you! Can we get a test to make sure this doesn't regress?

2022-08-31 21:08 UTC, vmagro commented
@LegNeato I added a test that is similar to other directive parsers, let me know if you had something else in mind

2022-08-31 21:42 UTC, bolinfest commented
@LegNeato once this lands, any chance we could get a new version of this crate pushed to crates.io along with a new version of `graphql-client` to pick up https://github.com/graphql-rust/graphql-client/pull/430?

2023-01-30 16:02 UTC, LegNeato approved these changes

2023-01-30 16:02 UTC, merged

2024-02-15 08:31 UTC, dotansimha commented
@LegNeato I think this PR was never included in a release? any chance we can get a release for that fix?