Introduce minify_query
graphql-rust/graphql-parser pull request #67
Opened 2022-08-03 13:23 UTC by kamilkisiela

Useful to reduce the size of payload

2022-08-04 15:06 UTC, LegNeato requested changes
Thank you! Can we get a test for the failure cases?

2022-08-23 10:43 UTC, kamilkisiela commented
@LegNeato here's the test for the failure case

2023-01-30 16:00 UTC, LegNeato approved these changes

2023-01-30 16:01 UTC, merged

2023-01-30 16:01 UTC, LegNeato commented
Thank you!